workflows:
  ios-native-workflow:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:

      groups:
        - admin

    scripts:

    - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
        script: keychain initialize

      - name: Fetch signing files
        script: app-store-connect fetch-signing-files "io.iosacademy.IOS-Academy" \
            --type IOS_APP_STORE \
            --create

      - name: Set up signing certificate
        script: keychain add-certificates

      - name: Set up code signing settings on Xcode project        
        script: xcode-project use-profiles 

      - name: Build App
        script: xcode-project build-ipa --workspace "IA.xcworkspace" --scheme "IA"
        
      - name: Install CocoaPods dependencies
        script: | 
          pod install
      
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:

      app_store_connect:
        api_key: $ APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $ APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $ APP_STORE_CONNECT_ISSUER_ID

        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
        submit_to_testflight: true

        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        submit_to_app_store: false
