workflows:
  ios-workflow:
    name: iOS Workflow 
    # ....
    environment:
      ios_signing:
        distribution_type: app_store # or: ad_hoc | development | enterprise
        bundle_identifier: CertificadoIOS

      vars:
        BUNDLE_ID: "io.codemagic.sample.iosnative"
        XCODE_WORKSPACE: "CodemagicSample.xcworkspace" # <-- Name of your Xcode workspace
        XCODE_SCHEME: "CodemagicSample" # <-- Name of your Xcode scheme
        
    scripts:
      # ...
      - name: Install dependencies cocoapods
        script: gem install cocoapods  # Instala CocoaPods si no está instalado

      - name: Install dependencies -repo-update
        script: pod install --repo-update  # Instala las dependencias de CocoaPods
        
      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      
      app_store_connect:
        auth: integration

        submit_to_testflight: true
        submit_to_app_store: false

integrations:
  app_store_connect:
    api_key:
      key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
      issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      private_key: $APP_STORE_CONNECT_PRIVATE_KEY
